### PR TITLE
Bump pcloud sdk to v1.8.1

### PR DESCRIPTION
**Pull request by hyproman**
**NOTE: pCloud auth does NOT currently work. The redirect_uri needs updating in the Kp2A pCloud app configuration**, which I do not have access to.

See here for more info:
      https://github.com/pCloud/pcloud-sdk-java/issues/33

### CODE REVIEW

**Comment by PhilippC** [comment]
in my understanding, we need to create a new "pcloud app" which has access to all folders, not just the KP2A folder as currently. the KP2A folder won't contain shared folders.

I did this (see https://github.com/PhilippC/keepass2android/commit/e3ae3233fee82d5601f3c355a290834be311dae8) but I got "5000 - internal error" when trying to list files in that new storage last week. This week I even get the same error for the existing file storage with app-folder access. I suspect that this is due to an issue with upgrading to 1.8.1, or do you have any other ideas @hyproman?

Unfortunately, it seems like

**Comment by hyproman** [comment]
@PhilippC Weird. I did a clean build of this code + your change and **eventually** I was able to authenticate using the "pcloudall" integration; I was able to browse my PCloud directory structure, open a shared database file, update it, sync it, etc.

I say **eventually** because for some reason the first attempt did not open the file chooser, but instead looped back to PCloud's login screen (after pressing Allow the first time). I tried logging in again and got a white screen forever. Unfortunately I didn't grab the logs on that attempt.

I'm wondering if maybe something is finicky on their end?

**Comment by PhilippC** [comment]
I can confirm that with a different account it seems to work fine. I have created https://github.com/pCloud/pcloud-sdk-java/issues/42

**Comment by PhilippC** [comment]
I have merged this code along with some updates I implemented.

**Comment by PhilippC** [comment]
note that shared folders still don't seem to work in my tests (https://github.com/pCloud/pcloud-sdk-java/issues/33#issuecomment-1794256245)

**Comment by PhilippC** [comment]
@gilbsgilbs I notice that the pCloud app has been created by you and it doesn't seem to support the new redirect-uri scheme which is required for this update to work. Could you please add this additional redirect uri in the app configuration:
`pcloud-oauth://keepass2android.keepass2android`? (Please don't remove any existing redirect URIs to keep compatibility with the current versions)

This is required so I can update the app. Thank you!

https://github.com/pCloud/pcloud-sdk-java/issues/33#issuecomment-1087395296

**Comment by gilbsgilbs** [comment]
I'd love to, but apparently they removed my account because of inactivity, I'm sorry. I guess the app is orphaned now…

I think it'd make sense if you took over the ownership of the OAuth2 app. If you don't want to create a new one, I can try to contact pCloud see if they let me recover the app.

**Pull request closed without merging**
