### PR TITLE
Mark passwords as sensitive when copy to clipboard

### PR DESCRIPTION
**Pull request by AriehSchneier**
This is to fix https://github.com/PhilippC/keepass2android/issues/2058
Fix https://github.com/PhilippC/keepass2android/issues/2071
Fix https://github.com/PhilippC/keepass2android/issues/2137

~I wasn't sure if I need to wrap the call to `.Extras` in an api version check >= 24, see [here](https://learn.microsoft.com/en-us/dotnet/api/android.content.clipdescription.extras?view=xamarin-android-sdk-12#android-content-clipdescription-extras), the [copy and paste](https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent) documentation didn't seem to think it was necessary?~ (Check added)

### CODE REVIEW

**Comment by AriehSchneier** [comment]
More reports:
Fix #2071 
Fix #2137 
Partial Fix #2102

**Comment by AriehSchneier** [comment]
I have now rebased on latest master, installed the artifact built in CI and tested locally.

**Review by PhilippC — CHANGES_REQUESTED** [review]
thanks for your pull request and sorry that I am replying so late!

I actually think there should be a check for API level 24. There are not too many people with Android <7, but there are, and I think chances are high that they will experience trouble if we don't check for this.

**Comment by AriehSchneier** [comment]
Added the API level 24 check and retested using the artifact built in CI on my phone (I don't have an android device with API version below 24 to test on).

**Pull request merged**
