### PR TITLE
Delete redundant and generated files

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Cleaned up .gitignore (removed duplicates, redundant statements like specified .suo files when *.suo was already there, etc.)
- Deleted all generated/old/redundant files in the Java folder (.idea, .gradle, .iml, etc.)

### CODE REVIEW

**Comment by PhilippC** [comment]
what's the purpose of all this? (I understand the purpose of cleaning things up, but why should I upgrade tools and libraries? Does it fix or improve anything?)

**Comment by TacoTheDank** [comment]
I mean, it's not really necessary, but it's a good thing to do regardless, because the new library versions (adal, onedrive, etc.) incorporate whatever bug fixes/other minor changes they made, and the plugins (gradles, etc.) were just outdated in general, and there's not really a reason *not* to update these, so...

Still, you can cherry-pick if you feel like leaving a few things out :)

**Comment by dave-kennedy** [comment]
It's always a good idea to stay on top of updates for security purposes. Also, the farther behind you get, the more work you'll have to do later when you finally want to update. As for cleaning up, it makes it easier for others to contribute if they don't have to wade through a bunch of dead code. It auto makes maintenance easier.

**Comment by aswild** [comment]
I was unable to build any of the Java code on Linux out of the box. The MIPS architectures were dropped from NDK r17, which necessitated updating to at least Gradle 4.4 and the Gradle plugin 3.1.0. I tried updating to the latest versions but that caused other problems.

All the Xamarin/Mono stuff was even worse, but that's a different story (it involved switching from xabuild to msbuild plus the evil deed of manually messing with package-manager controlled files in /usr).

I haven't looked into this particular PR, but I agree that it's generally good to keep build tools version up to date so that open-source projects are as easy for the community to build as possible.

**Comment by nift4** [comment]
@philippc Why is this not merged?

**Comment by TacoTheDank** [comment]
@nift4 At the moment, there's now multiple conflicts that are preventing the merge. As for PhilippC's side. I don't know. I'll have to fix them when I can.

**Comment by nift4** [comment]
Ah, I am on mobile. I don't see the conflicts. Nice that you kept intrest in merging for 10 months.

**Comment by PhilippC** [comment]
my experience with upgrades is that it requires lots of testing. Just because it compiles is not enough :-) The reason I often lack behind updates is that I don't have lots of time, but I agree it makes sense, of course.
However, when I checkout @TacoTheDank 's branch (without even merging wtih the latest changes) I cannot run build-java.bat in the build-scripts folder.
I get 
```
Could not resolve all files for configuration ':JavaFileStorage:debugCompileClasspath'.
> Could not find msal.jar (com.microsoft.identity.client:msal:0.1.2).
  Searched in the following locations:
      https://jcenter.bintray.com/com/microsoft/identity/client/msal/0.1.2/msal-0.1.2.jar

```

is it the same for you?

**Comment by nift4** [comment]
If you mean me, didn't try ;)

**Comment by TacoTheDank** [comment]
Rebased on top of latest commits, only did redundant file deletion this time.

**Comment by nift4** [comment]
Nice @TacoTheDank! Now it's your turn @PhillipC

**Pull request closed without merging**
