### PR TITLE
Update OkHttp to 4.10.0-RC1 to remove workaround for #747

### PR DESCRIPTION
**Pull request by lwis**
A fix has been pushed here https://github.com/square/okhttp/pull/6295

### CODE REVIEW

**Comment by lwis** [comment]
@PhilippC I'm having some trouble building, are you able to attach a test build here?

**Comment by lwis** [comment]
Brill, thanks @PhilippC!

If you're participating in Hacktoberfest, it would be great if you could add the label `hacktoberfest-accepted`.

**Comment by PhilippC** [comment]
I wasn't able to test this thoroughly. Could you please let me know if https://github.com/PhilippC/keepass2android/releases/tag/1.08c-r0 works for you? Do I need to sign up anywhere or can I just add that tag?

**Comment by lwis** [comment]
Thanks! Just tried the build, all my HTTP/2 related issues have been resolved 🎉 

You can just add the tag and it'll be picked up automatically.

**Pull request merged**
