### PR TITLE
Consolidate Gradle versions

### PR DESCRIPTION
**Pull request by hyproman**
This pull request consolidates the Gradle versions and configurations (somewhat) across keepass2android Java projects in order to cut down on the number of Gradle Daemon processes needed in order to build the project.

Before:
- **Gradle v4.10.3:**
    - JavaFileStorage
    - JavaFileStorageTest-AS
    - PluginQR
    - android-filechooser-AS
- **Gradle v5.4.1:**
    - Keepass2AndroidPluginSDK2
- **Gradle v6.1.1:**
    - KP2AKdbLibrary
    - KP2ASoftkeyboard_AS

After:
- **Gradle v5.0:**
    - JavaFileStorageTest-AS
    - PluginQR
    - android-filechooser-AS
- **Gradle v6.1.1**
    - JavaFileStorage
    - KP2AKdbLibrary
    - KP2ASoftkeyboard_AS
    - Keepass2AndroidPluginSDK2
 
Additionally the Gradle jvmargs across same-version projects have been normalized (this allows the daemon processes to be reused).

The versions were chosen based on trial and error; they were the highest versions I tried that allowed for a successful build without making more in-depth project modifications.

### CODE REVIEW

**Comment by tenzap** [comment]
please check latest master branch. It is likely some of your PR was already merged through #2203

**Comment by PhilippC** [comment]
@hyproman thanks for contributing. It looks like this overlapped with updates on the master branch which is why there are now conflicts. Can you please resolve these?

**Comment by hyproman** [comment]
Yeah, I realized just after submitting this that you all had been recently working a lot on the build environment, and you've superseded what I've done (which is great). I was just getting tired of running low on memory with 5 gradle processes running :)

Sadly, master will no longer build in linux: I believe it's due to Xamarin.Android for linux being behind on versions (from the available binaries on the site). I spent some time trying to build that from source, but to no avail.

I once again tried building this project on Windows 10. Building with command line fails (different errors than in linux). However I was able to get the latest version of VS to build it, after building the Java projects via command line. I will enter tickets with the failures with more details.

I am closing this PR out.

**Comment by tenzap** [comment]
Yes vs2022 is now mandatory. It doesn't build anymore on vs2019.

You should still be able to build locally on Linux if you set targetFrameworkversion to 12.0 or 11.0. more details here https://github.com/PhilippC/keepass2android/pull/2200

I found your attempt to have only one instance of gragle running interesting. Maybe you can still submit this? Updating the gradle wrapper may be of interest too.

**Pull request closed without merging**
