### PR TITLE
Update to latest FluentFTP version

### PR DESCRIPTION
**Pull request by hyproman**

### CODE REVIEW

**Comment by PhilippC** [comment]
@hyproman is this linked to any specific issue?

**Comment by hyproman** [comment]
@PhilippC It is indirectly related to #2423 

I was having trouble implementing the FluentFTP logging hooks with the version KP2A is using. It ended up being easier to update to the latest version, then follow the current documentation to do that. Ultimately the extra logging led to the minimal code to fix the bug (which is here: #2434). However the fix works on both versions of FluentFTP.

I created this PR rather than throw those changes away, but merging is not a strict requirement (it is not fixing a bug; rather housekeeping). I also opted not to completely hook the logging up; it could probably be done now that the SFTP debug logging UI toggle support has been added to **master**.

If you are okay letting this sit for a while longer, I will finish implementing that logging support when I get a chance.

**Comment by PhilippC** [comment]
@hyproman thanks for the explanation. I see you did implement a logger, what's left?

BTW for the upcoming release, is it ok if I add you to the contributors list and mention your work in the changelog? If so, which name should I use?

**Comment by hyproman** [comment]
@PhilippC I created the logger class but I haven't added the code to toggle it on and off from the UI. I had used it (hard-coded) in my debug builds to get to the bottom of the listing issue but left it disabled in this PR. I haven't had much time to get back to it, but I did see that it need to be implemented a bit different than the SFTP log toggle, so it wasn't a quick fix (at least for me). I'll take another crack at it, either tonight or tomorrow.

I'd be thrilled to be added to the contributors list! Rick Brown is good. Thanks!

**Comment by hyproman** [comment]
I've added the UI integration for enabling/disabling FTP debug logging.
This should be all set for review/merging.

**Pull request merged**
