### PR TITLE
Improve Argon2 performance

### PR DESCRIPTION
**Pull request by yan12125**
Fixes https://github.com/PhilippC/keepass2android/issues/106
Fixes https://github.com/PhilippC/keepass2android/issues/306

Before this patch, unlocking my database takes roughly 32 seconds, and with this patch unlocking the same database takes roughly 5 seconds only. My devices comes with Qualcomm Snapdrago 835 and my database uses 1000 iterations of time cost and 1048576 bytes of memory cost for Argon2 hashing.

The first commit is for fixing building this project on my machine. The actual Argon2 improvements are in the second commit. The first commit covers all changes proposed/mentioned in https://github.com/PhilippC/keepass2android/pull/836 and includes more fixes.

I skipped handling of `pbSecretKey` and `pbAssocData` as neither parameters are used in the KeePass.

### CODE REVIEW

**Comment by PhilippC** [comment]
thank you very much for implementing this!

**Comment by PhilippC** [comment]
do you want to be mentioned in the contributors list and/or changelog and if so, how?

**Comment by dayvan** [comment]
Yes, thank you to both!
You guys are the true heroes of the FOSS community 👍

**Comment by YellowOnion** [comment]
Brilliant! I just wished I knew the fix was this simple in the first place, and I might have tried it back when I first noticed the performance was rather bad.

I would recommend using the C# implementation as a fullback on the off chance someone has ported Android to a new architecture.

**Comment by yan12125** [comment]
> do you want to be mentioned in the contributors list and/or changelog and if so, how?

Glad to help :) Please mention me as Chih-Hsuan Yen, thanks!

> I would recommend using the C# implementation as a fullback on the off chance someone has ported Android to a new architecture.

I guess you're talking about something like RISC-V? The current Argon2 implementation uses plain C. In other words, no architecture-specific assembly is involved, so porting Keepass2Android to a new architecture should be simple.

**Comment by Offerel** [comment]
I can't wait to see this on the beta channel. BTW: Can the APK's be placed in the release section again?

**Comment by YellowOnion** [comment]
> I guess you're talking about something like RISC-V? The current Argon2 implementation uses plain C. In other words, no architecture-specific assembly is involved, so porting Keepass2Android to a new architecture should be simple.

It would be easier if the store app just worked right? But I guess the weak point is actually the mono runtime...But my point was portability of the apk release, not the source code.

**Comment by yan12125** [comment]
> It would be easier if the store app just worked right? But I guess the weak point is actually the mono runtime...But my point was portability of the apk release, not the source code.

Ah, yeah, mono requires more work as it's bigger. APKs on Google Play need to be recompiled from source to support a new architecture, anyway.

**Comment by rwat1** [comment]
@yan12125 Thank you, you are a life-saver and true hero to community.

My Xiaomi Mi 9T takes over 35 seconds to unlock my ARgon2 keepass file, whereas my laptop takes 1 second. No way is an AMD Ryzen some 35X faster than Snapdragon processor. 

It's great that you are able to fix it, thank you very much.

**Comment by Karreg** [comment]
> No way is an AMD Ryzen some 35X faster than Snapdragon processor.

In fact, it can. Because it makes no sense to compare pure computational power between CISC (x86 like your Ryzen) and RISC (ARM like your Snapdragon).

**Comment by rwat1** [comment]
> > No way is an AMD Ryzen some 35X faster than Snapdragon processor.
> 
> In fact, it can. Because it makes no sense to compare pure computational power between CISC (x86 like your Ryzen) and RISC (ARM like your Snapdragon).

Argon2 used to also take 1-2 seconds on my Samsung S9 which also has an ARM process (Snapdragon), so I highly doubt it's a slower processor.

**Comment by rwat1** [comment]
> > No way is an AMD Ryzen some 35X faster than Snapdragon processor.
> 
> In fact, it can. Because it makes no sense to compare pure computational power between CISC (x86 like your Ryzen) and RISC (ARM like your Snapdragon).

My Argon2 on Strongbox on iPhone XS took 1-2 seconds, so no, I don't think it's a matter of inferior processing speed.

**Comment by Karreg** [comment]
This is not a matter of speed, this is a matter of needed instructions. I'm trying to explain that your comparison makes no sense, so it is not a valid argument.
But I guess there's no point explaining... Also, it's already improved...

**Comment by rwat1** [comment]
Okay, thanks for the conversation.

**Comment by YellowOnion** [comment]
@Karreg [RISC v CISC](https://youtu.be/wPrUmViN_5c?t=45), what is this, 1995?

> This is not a matter of speed, this is a matter of needed instructions.

What kind of absurd statement is this? The result of having the right set of instructions _is_ speed, otherwise it doesn't matter.

And a history lesson for you, RISC was meant to be faster (which led to the quote in the movie), because it wasn't meant to be written by a human, and the IBM PowerPC architecture (a RISC design) did outperform x86 for years, which is why it was in game consoles, and supercomputers.

The RISC v CISC comparison doesn't matter in 2019, Speculative pipelines, out of order execution, cache hierarchies do, and most importantly power usage design envelope. An ARM CPU would be just as fast as Ryzen if it also used just as much power as they do, and I would happily gamble that ARM will surpass x86 in performance in a few years.

**Comment by yan12125** [comment]
Could we focus on Argon2 on Keepass2Android only? If you still get slow decryption or even crashes with KP2A 1.07 (the first version that includes this patch), feel free to blame me :) However, discussions about architectures bring little benefits to KP2A users IMO.

**Comment by rwat1** [comment]
When will the KP2A be updated?

**Comment by PhilippC** [comment]
it's in beta: https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by rwat1** [comment]
@PhilippC  I joined :)

It's my pleasure to report that Argon2 times have been reduced from 35 seconds to 7 seconds on Snapdragon 730 with 1200 iterations and 1MB and 2 parallelisms.

Thank you @yan12125

**Comment by Karreg** [comment]
Confirmed, that's great! Differences between desktop and mobile are smaller than for AES...

**Comment by chriswells0** [comment]
Any estimate for when the public build might be updated?  I've tested the app and it's great, so this is the only blocker for me to use it regularly.

**Comment by PhilippC** [comment]
I'm already rolling it out (step by step)

**Comment by chriswells0** [comment]
The difference here is amazing.  Thank you all so much!

**Comment by rwat1** [comment]
YESSS IT WORKSS!!!

**Comment by Ajedi32** [comment]
Wow. I recently received this update via the Play Store and upon unlocking my database I immediately went back to read the patch notes it was such a dramatic improvement. Thank you!

**Pull request merged**
