### PR TITLE
 Improved underscreen fingerprint, issue #831 

### PR DESCRIPTION
**Pull request by marcoDallas**
Improved underscreen fingerprint as requested in issue #831 by giving the users
the ability to disable the sensor in the PasswordActivity. Now pressing the
fingerprint icon opens up a dialog that has the option to enable/disable the
sensor.
I added two new strings to the resources (enable sensor - disable sensor) and
already translated them to Italian.

photo5949477682007879913
photo5949477682007879914

### CODE REVIEW

**Comment by PhilippC** [comment]
thanks for your pull request! Shouldn't this feature also be added in QuickUnlockActivity?

**Comment by marcoDallas** [comment]
Yes you're right, I missed that activity. I'm updating the pull request, thank you!

**Comment by marcoDallas** [comment]
Now it should be ready to be merged but let me know if you think it needs further improvements

**Comment by PhilippC** [comment]
looks good, thank you!

**Comment by PhilippC** [comment]
can I add "marcoDallas" in the list of contributors?

**Comment by marcoDallas** [comment]
Of course you can and I would be grateful if you do!

**Pull request merged**
