### PR TITLE
Replace YubiChallenge with ykDroid

### PR DESCRIPTION
**Pull request by pp3345**
This PR adds support for the ykDroid challenge-response driver. YubiChallenge is retained as a fallback if ykDroid is not installed on the device.

The main benefits of ykDroid over YubiChallenge are:
- USB is supported in addition to NFC (useful for tablets without NFC and allows to use any YubiKey with Android, even if it's not a NEO)
- Clean and Material Design-compliant UI with a non-interruptive overlay instead of a fullscreen activity

ykDroid is available on Google Play (also has screenshots of Keepass2Android with ykDroid): https://play.google.com/store/apps/details?id=net.pp3345.ykdroid
Source code of ykDroid is available on GitHub: https://github.com/pp3345/ykDroid

### CODE REVIEW

**Comment by PhilippC** [comment]
I have been planning to integrate Yubichallenge support directly into the main app for the implementation of the KeePassXC-compatible Challenge-Response. I will re-think this decision when I start working on that feature again.

**Comment by pp3345** [comment]
What exactly is still missing for KPXC challenge-response to work? I use KPXC myself but I am unable to unlock my database using KP2A. I'd be happy to help though.

**Comment by PhilippC** [comment]
it's already implemented in a local branch, will release to beta soon.

**Comment by PhilippC** [comment]
@pp3345 did you see https://github.com/pp3345/ykDroid/issues/2? Can you fix this? I would then test if ykDroid works with the new Challenge-Response implementation. I would prefer to have an external app handling the Yubikey stuff.

**Comment by pp3345** [comment]
@PhilippC Yes, I've seen it. I'm not at home right now but I will probably push a fix tomorrow evening.

**Comment by pp3345** [comment]
Closing this PR as it has become obsolete.

**Pull request closed without merging**
